### ISSUE TITLE
Produces too long string on MacOS

### ISSUE THREAD

**Issue by maratgumerof** [jonathanlermitage/intellij-battery-status-plugin#1]
I needed only Battery percentage, so I used this code:
`pmset -g batt | grep -Eo "\d+%"|echo "Battery:$(cat -)"`
I created a shell file and use this command in configuration: `bash /path/to/script.sh`
And now it works fine for me.

**Comment by jonathanlermitage** [comment]
Thx!  
I will try to add an option to use this script.

**Comment by jonathanlermitage** [comment]
Just published https://github.com/jonathanlermitage/intellij-battery-status-plugin/releases/tag/v1.6-snapshot1  
Could you make a try? I added an option in config panel to use your command in a temporary shell file.  
Thx!

**Comment by jonathanlermitage** [comment]
Sorry, uploaded a new snapshot https://github.com/jonathanlermitage/intellij-battery-status-plugin/releases/tag/v1.6-snapshot2

Previous build created a new tmp script at every battery status refresh :-p
