### ISSUE TITLE
Automatically toggle "Power Save Mode"?

### ISSUE THREAD

**Issue by Bouke** [jonathanlermitage/intellij-battery-status-plugin#5]
While looking through the IntelliJ Plugin Marketplace I found this plugin. I'm looking for a way to automatically toggle "Power Save Mode" whenever I'm on battery, maybe when the battery is below a certain percentage. This plugin seems somewhat related to such a feature, is this something that would fit this plugin?

**Comment by jonathanlermitage** [comment]
Sure, we can do this by invoking `ApplicationManager.getApplication().invokeLater(() -> PowerSaveMode.setEnabled(true), ModalityState.any());`

**Comment by jonathanlermitage** [comment]
Implemented. Will be part of 1.26 release.  
I added an option to enable/disable power saver when battery is low 

![screenshot-config-panel](https://user-images.githubusercontent.com/857535/229248209-2aec5a3f-7eb4-400d-a0e8-3d92d6b6c6a1.png)

**Comment by jonathanlermitage** [comment]
@Bouke I uploaded the 1.26 release: 
[Battery Status-1.26.zip](https://github.com/jonathanlermitage/intellij-battery-status-plugin/files/11128250/Battery.Status-1.26.zip), if you want to try it 😎  
It should be published to the plugin portal next week.
